/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZumbaRouteImport } from './routes/zumba'
import { Route as YogaRouteImport } from './routes/yoga'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PhysiotherapyRouteImport } from './routes/physiotherapy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ZumbaRoute = ZumbaRouteImport.update({
  id: '/zumba',
  path: '/zumba',
  getParentRoute: () => rootRouteImport,
} as any)
const YogaRoute = YogaRouteImport.update({
  id: '/yoga',
  path: '/yoga',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysiotherapyRoute = PhysiotherapyRouteImport.update({
  id: '/physiotherapy',
  path: '/physiotherapy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yoga': typeof YogaRoute
  '/zumba': typeof ZumbaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yoga': typeof YogaRoute
  '/zumba': typeof ZumbaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/physiotherapy': typeof PhysiotherapyRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/yoga': typeof YogaRoute
  '/zumba': typeof ZumbaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/physiotherapy'
    | '/services'
    | '/sitemap.xml'
    | '/yoga'
    | '/zumba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/physiotherapy'
    | '/services'
    | '/sitemap.xml'
    | '/yoga'
    | '/zumba'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/physiotherapy'
    | '/services'
    | '/sitemap.xml'
    | '/yoga'
    | '/zumba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PhysiotherapyRoute: typeof PhysiotherapyRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  YogaRoute: typeof YogaRoute
  ZumbaRoute: typeof ZumbaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zumba': {
      id: '/zumba'
      path: '/zumba'
      fullPath: '/zumba'
      preLoaderRoute: typeof ZumbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yoga': {
      id: '/yoga'
      path: '/yoga'
      fullPath: '/yoga'
      preLoaderRoute: typeof YogaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physiotherapy': {
      id: '/physiotherapy'
      path: '/physiotherapy'
      fullPath: '/physiotherapy'
      preLoaderRoute: typeof PhysiotherapyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PhysiotherapyRoute: PhysiotherapyRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  YogaRoute: YogaRoute,
  ZumbaRoute: ZumbaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
